language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

install: composer update --no-dev --no-interaction

script: phpunit --coverage-text

addons:
    code_climate:
        repo_token: 6f2d5e4aa8c190542beb482ac6c1c1cc9b2f896c9d3c64c02e2bd2ec3f5757eb

after_script:
  - vendor/bin/test-reporter